asname: Deploy to EC2

on:
  push:
    branches:
      - main  # ←あなたのブランチが main なのでこれでOK！Elasticに変更しました！

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/myfitnote
            git pull origin main
            npm install
            pm2 restart all || pm2 start app.js --name myfitnote
