name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ec2-user/myfitnote
          git pull origin main
          docker rm -f myfitnote-container || true
          docker build -t myfitnote-app .
          docker run -d -p 3000:3000 --env-file .env --name myfitnote-container myfitnote-app
